 #-------------------------------------------------------------------------
 # MPLAB XC Compiler -  PIC32MK0512MCF100 vector-offset initialization module
 # 
 # Copyright (c) 2021, Microchip Technology Inc. and its subsidiaries ("Microchip")
 # All rights reserved.
 # 
 # This software is developed by Microchip Technology Inc. and its
 # subsidiaries ("Microchip").
 # 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are 
 # met:
 # 
 # 1.      Redistributions of source code must retain the above copyright
 #         notice, this list of conditions and the following disclaimer.
 # 2.      Redistributions in binary form must reproduce the above 
 #         copyright notice, this list of conditions and the following 
 #         disclaimer in the documentation and/or other materials provided 
 #         with the distribution. Publication is not required when this file 
 #         is used in an embedded application.
 # 3.      Microchip's name may not be used to endorse or promote products
 #         derived from this software without specific prior written 
 #         permission.
 # 
 # THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED
 # WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR PURPOSE ARE DISCLAIMED. IN NO EVENT 
 # SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 # EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 # PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS;
 # OR BUSINESS INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 # WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 # 
 #

 #-------------------------------------------------------------------------


  .section .__vector_offset_BF810540_data,data,keep,address(0xBF810540)
  .word __vector_offset_0
  .word __vector_offset_1
  .word __vector_offset_2
  .word __vector_offset_3
  .word __vector_offset_4
  .word __vector_offset_5
  .word __vector_offset_6
  .word __vector_offset_7
  .word __vector_offset_8
  .word __vector_offset_9
  .word __vector_offset_10
  .word __vector_offset_11
  .word __vector_offset_12
  .word __vector_offset_13
  .word __vector_offset_14
  .word __vector_offset_15
  .word __vector_offset_16
  .word __vector_offset_17
  .word __vector_offset_18
  .word __vector_offset_19
  .word __vector_offset_20
  .word __vector_offset_21
  .word __vector_offset_22
  .word __vector_offset_23
  .word __vector_offset_24
  .word __vector_offset_25
  .word __vector_offset_26
  .word __vector_offset_27
  .section .__vector_offset_BF8105B8_data,data,keep,address(0xBF8105B8)
  .word __vector_offset_30
  .word __vector_offset_31
  .word __vector_offset_32
  .word __vector_offset_33
  .word __vector_offset_34
  .word __vector_offset_35
  .word __vector_offset_36
  .word __vector_offset_37
  .word __vector_offset_38
  .word __vector_offset_39
  .word __vector_offset_40
  .word __vector_offset_41
  .word __vector_offset_42
  .word __vector_offset_43
  .word __vector_offset_44
  .word __vector_offset_45
  .word __vector_offset_46
  .word __vector_offset_47
  .word __vector_offset_48
  .word __vector_offset_49
  .word __vector_offset_50
  .word __vector_offset_51
  .word __vector_offset_52
  .word __vector_offset_53
  .word __vector_offset_54
  .word __vector_offset_55
  .word __vector_offset_56
  .word __vector_offset_57
  .word __vector_offset_58
  .word __vector_offset_59
  .word __vector_offset_60
  .word __vector_offset_61
  .word __vector_offset_62
  .word __vector_offset_63
  .word __vector_offset_64
  .word __vector_offset_65
  .word __vector_offset_66
  .word __vector_offset_67
  .word __vector_offset_68
  .word __vector_offset_69
  .word __vector_offset_70
  .word __vector_offset_71
  .word __vector_offset_72
  .word __vector_offset_73
  .word __vector_offset_74
  .word __vector_offset_75
  .word __vector_offset_76
  .word __vector_offset_77
  .word __vector_offset_78
  .word __vector_offset_79
  .word __vector_offset_80
  .word __vector_offset_81
  .word __vector_offset_82
  .word __vector_offset_83
  .word __vector_offset_84
  .word __vector_offset_85
  .word __vector_offset_86
  .word __vector_offset_87
  .word __vector_offset_88
  .word __vector_offset_89
  .word __vector_offset_90
  .word __vector_offset_91
  .word __vector_offset_92
  .word __vector_offset_93
  .word __vector_offset_94
  .word __vector_offset_95
  .word __vector_offset_96
  .word __vector_offset_97
  .word __vector_offset_98
  .word __vector_offset_99
  .word __vector_offset_100
  .word __vector_offset_101
  .word __vector_offset_102
  .word __vector_offset_103
  .word __vector_offset_104
  .word __vector_offset_105
  .word __vector_offset_106
  .word __vector_offset_107
  .word __vector_offset_108
  .word __vector_offset_109
  .word __vector_offset_110
  .word __vector_offset_111
  .word __vector_offset_112
  .word __vector_offset_113
  .word __vector_offset_114
  .word __vector_offset_115
  .word __vector_offset_116
  .word __vector_offset_117
  .word __vector_offset_118
  .word __vector_offset_119
  .word __vector_offset_120
  .word __vector_offset_121
  .word __vector_offset_122
  .word __vector_offset_123
  .word __vector_offset_124
  .word __vector_offset_125
  .word __vector_offset_126
  .word __vector_offset_127
  .word __vector_offset_128
  .word __vector_offset_129
  .word __vector_offset_130
  .word __vector_offset_131
  .word __vector_offset_132
  .word __vector_offset_133
  .section .__vector_offset_BF81076C_data,data,keep,address(0xBF81076C)
  .word __vector_offset_139
  .word __vector_offset_140
  .word __vector_offset_141
  .word __vector_offset_142
  .word __vector_offset_143
  .word __vector_offset_144
  .word __vector_offset_145
  .word __vector_offset_146
  .word __vector_offset_147
  .section .__vector_offset_BF81079C_data,data,keep,address(0xBF81079C)
  .word __vector_offset_151
  .word __vector_offset_152
  .word __vector_offset_153
  .word __vector_offset_154
  .word __vector_offset_155
  .word __vector_offset_156
  .word __vector_offset_157
  .word __vector_offset_158
  .word __vector_offset_159
  .word __vector_offset_160
  .word __vector_offset_161
  .word __vector_offset_162
  .section .__vector_offset_BF8107D0_data,data,keep,address(0xBF8107D0)
  .word __vector_offset_164
  .word __vector_offset_165
  .word __vector_offset_166
  .word __vector_offset_167
  .word __vector_offset_168
  .word __vector_offset_169
  .word __vector_offset_170
  .word __vector_offset_171
  .word __vector_offset_172
  .word __vector_offset_173
  .word __vector_offset_174
  .word __vector_offset_175
  .word __vector_offset_176
  .word __vector_offset_177
  .word __vector_offset_178
  .word __vector_offset_179
  .word __vector_offset_180
  .word __vector_offset_181
  .word __vector_offset_182
  .word __vector_offset_183
  .word __vector_offset_184
  .word __vector_offset_185
  .word __vector_offset_186
  .word __vector_offset_187
  .word __vector_offset_188
  .word __vector_offset_189
  .word __vector_offset_190
  .word __vector_offset_191
  .word __vector_offset_192
  .section .__vector_offset_BF810848_data,data,keep,address(0xBF810848)
  .word __vector_offset_194
  .word __vector_offset_195
  .word __vector_offset_196
  .word __vector_offset_197
  .word __vector_offset_198
  .word __vector_offset_199
  .word __vector_offset_200
  .word __vector_offset_201
  .word __vector_offset_202
  .word __vector_offset_203
  .word __vector_offset_204
  .word __vector_offset_205
  .word __vector_offset_206
  .word __vector_offset_207
  .word __vector_offset_208
  .word __vector_offset_209
  .word __vector_offset_210
  .word __vector_offset_211
  .word __vector_offset_212
  .word __vector_offset_213
  .word __vector_offset_214
  .word __vector_offset_215
  .word __vector_offset_216
  .word __vector_offset_217
  .word __vector_offset_218
  .word __vector_offset_219
  .word __vector_offset_220
  .word __vector_offset_221
  .word __vector_offset_222
  .word __vector_offset_223
  .word __vector_offset_224
  .word __vector_offset_225
  .word __vector_offset_226
  .word __vector_offset_227
  .word __vector_offset_228
  .word __vector_offset_229
  .word __vector_offset_230
  .section .__vector_offset_BF8108F8_data,data,keep,address(0xBF8108F8)
  .word __vector_offset_238
  .word __vector_offset_239
  .word __vector_offset_240
  .word __vector_offset_241
  .word __vector_offset_242
  .word __vector_offset_243
  .word __vector_offset_244
  .word __vector_offset_245
  .word __vector_offset_246
  .section .__vector_offset_BF810938_data,data,keep,address(0xBF810938)
  .word __vector_offset_254
  .word __vector_offset_255


