 #-------------------------------------------------------------------------
 # MPLAB XC Compiler -  PIC32MZ1025W104132 vector-offset initialization module
 # 
 # Copyright (c) 2020, Microchip Technology Inc. and its subsidiaries ("Microchip")
 # All rights reserved.
 # 
 # This software is developed by Microchip Technology Inc. and its
 # subsidiaries ("Microchip").
 # 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are 
 # met:
 # 
 # 1.      Redistributions of source code must retain the above copyright
 #         notice, this list of conditions and the following disclaimer.
 # 2.      Redistributions in binary form must reproduce the above 
 #         copyright notice, this list of conditions and the following 
 #         disclaimer in the documentation and/or other materials provided 
 #         with the distribution.
 # 3.      Microchip's name may not be used to endorse or promote products
 #         derived from this software without specific prior written 
 #         permission.
 # 
 # THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED
 # WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 # MERCHANTABILITY AND FITNESS FOR PURPOSE ARE DISCLAIMED. IN NO EVENT 
 # SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 # EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
 # PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS;
 # OR BUSINESS INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 # WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
 # OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 # 
 #

 #-------------------------------------------------------------------------


  .section .__vector_offset_BF810540_data,data,keep,address(0xBF810540)
  .word __vector_offset_0
  .word __vector_offset_1
  .word __vector_offset_2
  .word __vector_offset_3
  .word __vector_offset_4
  .word __vector_offset_5
  .word __vector_offset_6
  .word __vector_offset_7
  .word __vector_offset_8
  .word __vector_offset_9
  .word __vector_offset_10
  .word __vector_offset_11
  .word __vector_offset_12
  .word __vector_offset_13
  .word __vector_offset_14
  .word __vector_offset_15
  .word __vector_offset_16
  .word __vector_offset_17
  .word __vector_offset_18
  .word __vector_offset_19
  .word __vector_offset_20
  .word __vector_offset_21
  .word __vector_offset_22
  .word __vector_offset_23
  .word __vector_offset_24
  .section .__vector_offset_BF8105B8_data,data,keep,address(0xBF8105B8)
  .word __vector_offset_30
  .word __vector_offset_31
  .word __vector_offset_32
  .word __vector_offset_33
  .word __vector_offset_34
  .word __vector_offset_35
  .word __vector_offset_36
  .word __vector_offset_37
  .word __vector_offset_38
  .word __vector_offset_39
  .word __vector_offset_40
  .word __vector_offset_41
  .word __vector_offset_42
  .word __vector_offset_43
  .word __vector_offset_44
  .word __vector_offset_45
  .word __vector_offset_46
  .word __vector_offset_47
  .section .__vector_offset_BF810614_data,data,keep,address(0xBF810614)
  .word __vector_offset_53
  .word __vector_offset_54
  .word __vector_offset_55
  .word __vector_offset_56
  .word __vector_offset_57
  .word __vector_offset_58
  .word __vector_offset_59
  .word __vector_offset_60
  .word __vector_offset_61
  .word __vector_offset_62
  .word __vector_offset_63
  .word __vector_offset_64
  .section .__vector_offset_BF810650_data,data,keep,address(0xBF810650)
  .word __vector_offset_68
  .word __vector_offset_69
  .word __vector_offset_70
  .word __vector_offset_71
  .word __vector_offset_72
  .word __vector_offset_73
  .word __vector_offset_74
  .word __vector_offset_75
  .word __vector_offset_76
  .section .__vector_offset_BF810680_data,data,keep,address(0xBF810680)
  .word __vector_offset_80
  .section .__vector_offset_BF81068C_data,data,keep,address(0xBF81068C)
  .word __vector_offset_83
  .word __vector_offset_84
  .word __vector_offset_85
  .word __vector_offset_86
  .word __vector_offset_87
  .word __vector_offset_88
  .word __vector_offset_89
  .word __vector_offset_90
  .word __vector_offset_91
  .word __vector_offset_92
  .section .__vector_offset_BF8106B8_data,data,keep,address(0xBF8106B8)
  .word __vector_offset_94
  .word __vector_offset_95
  .word __vector_offset_96
  .word __vector_offset_97
  .section .__vector_offset_BF8106D0_data,data,keep,address(0xBF8106D0)
  .word __vector_offset_100
  .word __vector_offset_101
  .word __vector_offset_102
  .word __vector_offset_103
  .word __vector_offset_104
  .section .__vector_offset_BF8106E8_data,data,keep,address(0xBF8106E8)
  .word __vector_offset_106
  .word __vector_offset_107
  .word __vector_offset_108
  .word __vector_offset_109
  .word __vector_offset_110
  .word __vector_offset_111
  .word __vector_offset_112
  .word __vector_offset_113
  .word __vector_offset_114
  .word __vector_offset_115
  .word __vector_offset_116
  .word __vector_offset_117
  .word __vector_offset_118
  .word __vector_offset_119
  .word __vector_offset_120
  .word __vector_offset_121
  .word __vector_offset_122
  .word __vector_offset_123
  .word __vector_offset_124
  .word __vector_offset_125
  .word __vector_offset_126
  .word __vector_offset_127
  .word __vector_offset_128
  .word __vector_offset_129
  .section .__vector_offset_BF810778_data,data,keep,address(0xBF810778)
  .word __vector_offset_142
  .word __vector_offset_143
  .word __vector_offset_144
  .word __vector_offset_145
  .section .__vector_offset_BF810798_data,data,keep,address(0xBF810798)
  .word __vector_offset_150
  .section .__vector_offset_BF8107A0_data,data,keep,address(0xBF8107A0)
  .word __vector_offset_152
  .word __vector_offset_153
  .word __vector_offset_154
  .word __vector_offset_155
  .word __vector_offset_156
  .word __vector_offset_157
  .section .__vector_offset_BF8107C8_data,data,keep,address(0xBF8107C8)
  .word __vector_offset_162
  .word __vector_offset_163
  .word __vector_offset_164
  .word __vector_offset_165
  .word __vector_offset_166
  .word __vector_offset_167


